name: Workflow commands demo

on: [push]
env: 
    MY_VAR: "TestThis WORKFLOW LEVEL"

jobs:
    set-env:
        runs-on: ubuntu-latest
        env: 
            MY_VAR: "TestThis SETENV JOB"
        steps:
          - name: Set environment variable
            run: |
                echo "This is a log message for the set-env job $MY_VAR"
                echo "MY_VAR2=Hello from the environment variable!" >> $GITHUB_ENV
                echo "MYVAR2 logs ${{env.MY_VAR2}}"
    workflow-commands:
        runs-on: ubuntu-latest
        steps:
          - name: group logging
            run: |
              echo "This is a log message outside of the group."
              echo "::group::This is the start of the group."
              echo "This is a log message inside the group."
              echo "::endgroup::This is the end of the group."
              echo "This is a log message for the set-env job $MY_VAR"
