name: Workflow commands demo - variables
on: [push]
env: 
    MY_VAR: "TestThis WORKFLOW LEVEL"

jobs:
    set-env:
        runs-on: ubuntu-latest
        env: 
            MY_VAR: "JOB LEVEL MYVAR"
        steps:
          - name: Set environment variable
            run: |
                echo "This is a log message for the set-env job $MY_VAR"
                echo "MY_VAR2=MYVAR2 JOB LEVEL!" >> $GITHUB_ENV
          - name: Echo MY_VAR2
            run: echo "MYVAR2 logs $MY_VAR2"
    workflow-commands:
        runs-on: ubuntu-latest
        steps:
          - name: group logging
            run: |
              echo "This is a log message for the set-env job ${{env.MY_VAR}}"
              echo "This is a log message for the set-env job MYVAR2 ${{env.MY_VAR2}}" 
              echo "This is a log message for the set-env job BRANCH ${{env.BRANCH}}"   
            env:
              ACTION_ACTOR: ${{ github.actor }}
              BRANCH: ${{ github.ref }}
            
