name: Workflow commands demo

on: [push]

jobs:
    set-env:
        runs-on: ubuntu-latest
        env: 
            MY_VAR: "TestThis SETENV JOB"
        steps:
          - name: Set environment variable
            run: echo "MY_VAR=Hello from the environment variable!" >> $GITHUB_ENV
                echo "This is a log message for the set-env job $MY_VAR."
    workflow-commands:
        runs-on: ubuntu-latest
        steps:
          - name: group logging
            run: |
              echo "This is a log message outside of the group."
              echo "::group::This is the start of the group."
              echo "This is a log message inside the group."
              echo "::endgroup::This is the end of the group."
              echo "This is another log message outside of the group for $MY_VAR."